# preparation

In [1]:
# ! pip install kaggle
# ! apt install zip unzip

In [2]:
import os
import json

with open("token/kaggle.json", mode="r") as f:
    json_data = json.load(f)
os.environ["KAGGLE_USERNAME"] = json_data["username"]
os.environ["KAGGLE_KEY"] = json_data["key"]

In [3]:
# ! kaggle competitions download -c allstate-claims-severity
# ! unzip allstate-claims-severity.zip

# EDA

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [5]:
train_df = pd.read_csv('train.csv', index_col='id')
test_df = pd.read_csv('test.csv', index_col='id')

In [6]:
train_df

,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,cat10,...,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,cont14,loss
id,,,,,,,,,,,,,,,,,,,,,
1,A,B,A,B,A,A,A,A,B,A,...,0.718367,0.335060,0.30260,0.67135,0.83510,0.569745,0.594646,0.822493,0.714843,2213.18
2,A,B,A,A,A,A,A,A,B,B,...,0.438917,0.436585,0.60087,0.35127,0.43919,0.338312,0.366307,0.611431,0.304496,1283.60
5,A,B,A,A,B,A,A,A,B,B,...,0.289648,0.315545,0.27320,0.26076,0.32446,0.381398,0.373424,0.195709,0.774425,3005.09
10,B,B,A,B,A,A,A,A,B,A,...,0.440945,0.391128,0.31796,0.32128,0.44467,0.327915,0.321570,0.605077,0.602642,939.85
11,A,B,A,B,A,A,A,A,B,B,...,0.178193,0.247408,0.24564,0.22089,0.21230,0.204687,0.202213,0.246011,0.432606,2763.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587620,A,B,A,A,A,A,A,A,B,A,...,0.242437,0.289949,0.24564,0.30859,0.32935,0.223038,0.220003,0.333292,0.208216,1198.62
587624,A,A,A,A,A,B,A,A,A,A,...,0.334270,0.382000,0.63475,0.40455,0.47779,0.307628,0.301921,0.318646,0.305872,1108.34
587630,A,B,A,A,A,A,A,B,B,A,...,0.345883,0.370534,0.24564,0.45808,0.47779,0.445614,0.443374,0.339244,0.503888,5762.64
587632,A,B,A,A,A,A,A,A,B,B,...,0.704364,0.562866,0.34987,0.44767,0.53881,0.863052,0.852865,0.654753,0.721707,1562.87
587633,B,A,A,B,A,A,A,A,A,A,...,0.844563,0.533048,0.97123,0.93383,0.83814,0.932195,0.946432,0.810511,0.721460,4751.72

In [7]:
train_df.info() # show all col dtype param: verbose=True

<class 'pandas.core.frame.DataFrame'>
Int64Index: 188318 entries, 1 to 587633
Columns: 131 entries, cat1 to loss
dtypes: float64(15), object(116)
memory usage: 189.7+ MB

In [8]:
print(f"\
      train_df:{train_df.isnull().values.any()} \n \
      test_df:{test_df.isnull().values.any()} \n \
      ")

      train_df:False
       test_df:False

In [ ]:
fig, ax = plt.subplots(figsize=(20, 10))
sns.histplot(train_df['loss'], ax=ax, kde=True)

## split num_cal and cat_cal

In [ ]:
# create numerical data frame
numerical_cols = [cname for cname in train_df.columns
                  if train_df[cname].dtype == 'float64']

In [ ]:
train_df_numcols = train_df[numerical_cols].copy()
train_df_numcols

In [ ]:
# create categorical data frame
categorical_cols = [cname for cname in train_df.columns
                    if train_df[cname].dtype == "object"]

In [ ]:
train_df_catcols = train_df[categorical_cols].copy()
train_df_catcols

## print overview

In [ ]:
# ! pip install pandas-profiling
import pandas_profiling as pdp

In [ ]:
# pdp.ProfileReport(train_df)

In [ ]:
# profile = _
# profile.to_file("train_df_profiling")

In [ ]:
# sns.pairplot(train_df_numcols)

In [ ]:
# pg = _
# pg.savefig('train_df_numcols-pairplot.png')